Bug 1, inside smithyCard():

Description: Player draws 4 cards instead of 3.

This was discovered running my unit test cardtest1. All inputs produced
a similar result. Here is one example test, which printed:

        ----------------- Testing Card: smithy ----------------
        hand count = 8, expected = 7
        ***FAILED ASSERTION: 8 == 7***
        deck count = 1, expected = 2
        ***FAILED ASSERTION: 1 == 2***

We can see that the hand count is 1 greater than expected.
Also, the deck count is 1 less than expected.
A simple conclusion could be that the player drew 1 extra card from the deck to their hand.
Looking, at the code within smithyCard(), we see that this is indeed the case.
The for-loop to draw cards is executed 4 times instead of 3.

        for (i = 0; i <= 3; i++)
        {
          drawCard(currentPlayer, state);
        }

////////////////////////////////////////////////////////////////

Bug 2, inside adventurerCard():

Description: The played adventurer card is never discarded.

This was discovered running my unit test cardtest2. All inputs produced
a similar result. Here is one example test, which printed:

        ----------------- Testing Card: adventurer ----------------
        hand count = 7, expected = 6
        ***FAILED ASSERTION: 7 == 6***
        number of treasures in hand = 6, expected = 6
        deckCount + discardCount = 3 + 0, expected = 3
        played cards pile count = 0, expected = 1
        ***FAILED ASSERTION: 0 == 1***

We can see that the hand count is 1 greater than expected.
Also, the played cards pile is 1 less than expected.
Looking at the code inside adventurerCard(), we can see That
discardCard() is never called.

/////////////////////////////////////////////////////////////////

Bug 3, inside great_hallCard():

Description: Player never draws a card.

This was discovered running my unit test cardtest4. All inputs produced
a similar result. Here is one example test, which printed:

        ----------------- Testing Card: great_hall ----------------
        hand count = 4, expected = 5
        ***FAILED ASSERTION: 4 == 5***
        deck count = 5, expected = 4
        ***FAILED ASSERTION: 5 == 4***

We can see that the hand count is 1 less than expected.
Also, the deck count is 1 greater than expected.
Looking at the code inside great_hallCard(), we can see that drawCard()
is never called.
